In [2]:
import pandas as pd
import numpy as np

In [3]:
df = pd.read_csv('Airplane_Crashes.csv')
df

,index,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,1,07/12/1912,06:30,"AtlantiCity, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
2,2,08/06/1913,NaN,"Victoria, British Columbia, Canada",Private,-,NaN,Curtiss seaplane,NaN,NaN,1.0,1.0,0.0,The first fatal airplane accident in Canada oc...
3,3,09/09/1913,18:30,Over the North Sea,Military - German Navy,NaN,NaN,Zeppelin L-1 (airship),NaN,NaN,20.0,14.0,0.0,The airship flew into a thunderstorm and encou...
4,4,10/17/1913,10:30,"Near Johannisthal, Germany",Military - German Navy,NaN,NaN,Zeppelin L-2 (airship),NaN,NaN,30.0,30.0,0.0,Hydrogen gas which was being vented was sucked...
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5263,5263,05/20/2009,06:30,"Near Madiun, Indonesia",Military - Indonesian Air Force,NaN,Jakarta - Maduin,Lockheed C-130 Hercules,A-1325,1982,112.0,98.0,2.0,"While on approach, the military transport cras..."
5264,5264,05/26/2009,NaN,"Near Isiro, DemocratiRepubliCongo",Service Air,NaN,Goma - Isiro,Antonov An-26,9Q-CSA,5005,4.0,4.0,NaN,The cargo plane crashed while on approach to I...
5265,5265,06/01/2009,00:15,"AtlantiOcean, 570 miles northeast of Natal, Br...",Air France,447,Rio de Janeiro - Paris,Airbus A330-203,F-GZCP,660,228.0,228.0,0.0,The Airbus went missing over the AtlantiOcean ...
5266,5266,06/07/2009,08:30,"Near Port Hope Simpson, Newfoundland, Canada",Strait Air,NaN,Lourdes de BlanSablon - Port Hope Simpson,Britten-Norman BN-2A-27 Islander,C-FJJR,424,1.0,1.0,0.0,The air ambulance crashed into hills while att...
5267,5267,06/08/2009,NaN,"State of Arunachal Pradesh, India",Military - Indian Air Force,NaN,Mechuka for Jorhat,Antonov An-32,NaN,NaN,13.0,13.0,0.0,The military transport went missing while en r...

In [6]:
wroute = df[df["Route"].notna()]
wroute.head(20)

,index,Date,Time,Location,Operator,Flight #,Route,Type,Registration,cn/In,Aboard,Fatalities,Ground,Summary
0,0,09/17/1908,17:18,"Fort Myer, Virginia",Military - U.S. Army,NaN,Demonstration,Wright Flyer III,NaN,1,2.0,1.0,0.0,"During a demonstration flight, a U.S. Army fly..."
1,1,07/12/1912,06:30,"AtlantiCity, New Jersey",Military - U.S. Navy,NaN,Test flight,Dirigible,NaN,NaN,5.0,5.0,0.0,First U.S. dirigible Akron exploded just offsh...
56,56,09/06/1921,NaN,"Paris, France",Franco-Roumaine,NaN,Varsovie - Strasbourg - Paris,Potez IX,F-ADCD,160,5.0,5.0,0.0,Crashed while making an approach to Le Bourget...
80,80,12/23/1923,02:30,Over the Mediterranean Sea,Military - French Navy,NaN,Toulon - Algiers,Zeppelin Dixmunde (airship),L-72,NaN,52.0,52.0,0.0,"Crashed while on a flight from Toulon, France ..."
83,83,04/24/1924,NaN,Over the English Channel,KLM Royal Dutch Airlines,NaN,"Lympne, England - Rotterdam, The Netherlands",Fokker F.III,H-NABS,1535,3.0,3.0,0.0,NaN
96,96,09/03/1925,05:30,"Caldwell, Ohio",Military - U.S. Navy,NaN,"Lakehurst, NJ - S.t Louis, MO",Dirigible ZR-1 Shenandoah (airship),ZR-1,NaN,43.0,14.0,0.0,The Shenandoah was flying over Southern Ohio w...
102,102,07/03/1926,NaN,"Rossaugpt, Czechoslovakia",Compagnie Internationale de Navigation AÃ©rienne,NaN,Paris - Prague,Caudron C-61,F-AFBT,5307,7.0,7.0,0.0,Crashed while en route.
106,106,09/26/1926,NaN,"New York, New York",NaN,NaN,New York - Paris,Sikorsky S-25,NaN,NaN,5.0,2.0,0.0,Too much weight caused the landing gear to col...
119,119,08/22/1927,08:30,"Sevenoaks, England",KLM Royal Dutch Airlines,NaN,Croydon - Schiphol,Fokker F-VIII,NaN,4993,11.0,1.0,0.0,A broken wire led to the partial loss of the t...
121,121,09/17/1927,NaN,"Hadley, New Jersey",Reynolds Airways,NaN,Sightseeing,Fokker F-VII,NC776,4840,12.0,7.0,0.0,The sightseeing plane took off and rose to 400...
123,123,09/23/1927,10:00,"Schleiz, Germany",Deutsche Lufthansa,NaN,Berlin - Munich,Dornier Merkur,D-585,NaN,6.0,6.0,0.0,Broken wing strut.
132,132,01/08/1928,NaN,"Near Canajoharie, New York",Colonial Western Airlines,NaN,Minola - Albany - Buffalo,Fairchild FC-2,NaN,39,3.0,3.0,0.0,Became lost in dense fog and flew into the gro...
146,146,06/22/1928,NaN,"Lebo, Kansas",National Air Transport,NaN,Chicago - Dallas,Douglas M-4,NaN,NaN,1.0,1.0,0.0,The mail plane flew into tornado like winds an...
148,148,07/13/1928,NaN,"Purley, England",Imperial Airways,NaN,Testing,Vickers 74 Vulcan,G-EBLB,9,4.0,4.0,0.0,Crashed to the ground shortly after taking off...
150,150,08/25/1928,NaN,"Near Port Townsend, BC, Canada",British Columbia Airways,NaN,Victoria - Seattle,Ford 4-AT-B Tri Motor,G-CATX,4-AT-26,7.0,7.0,0.0,Crashed into Puget Sound in dense fog. Consid...
159,159,11/24/1928,NaN,"Edgerton, Ohio",Universal Airlines,NaN,Cleveland - Chicago,Hamilton H-47,NaN,46,3.0,3.0,0.0,The mail plane crashed in a heavy snow storm.
161,161,11/25/1928,NaN,"Edgerton, Ohio",Continental Air Lines,NaN,Cleveland - Louisville,Travel Air 4000,NaN,NaN,3.0,3.0,0.0,The mail plane crashed in a heavy snow storm
162,162,12/01/1928,10:00,"Spur, Texas",Sunbeam Air Transport Co.,NaN,San Antonio - Amarillo - Tulsa - Denver,Ford 4-AT-B Tri Motor,NC7862,4-AT-47,5.0,5.0,0.0,The aircraft crashed and burned while en route...
166,166,12/20/1928,NaN,"Huron, Ohio",National Air Transport,NaN,Cleveland - Chicago,Douglas M-4,NaN,NaN,1.0,1.0,0.0,The mail plane crashed into an apple tree duri...
174,174,03/17/1929,NaN,"Newark, New Jersey",Colonial Western Airlines,NaN,Sightseeing,Ford 5-AT-B Tri Motor,NC7683,4-AT-41,15.0,14.0,0.0,The plane was making the last of a number of s...

In [7]:
wroute["Route"].isna().sum()

0

In [10]:
wroute["Flight #"].isna().sum()

2538